// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using SIS.OpenCore.Shared.Model.Common;
using SIS.OpenCore.Shared.Model.Objects.CIF;

#nullable disable

namespace SIS.OpenCore.Shared.Model.Objects.Account.CK
{
    public partial class DEF_CK_ACCT : BaseCIFACCT //BaseCIFACCT
    {
        override public int GetPrimaryKey ()
        {
            return DEF_ACCT_ID;
        }
        public int DEF_ACCT_ID { get; set; }
        public string CIF_NO { get; set; }
        public short ACCT_CLASS_ID { get; set; }
        public short CompanyID { get; set; }
        public string ACCT_NO { get; set; }
        public string Currency { get; set; }
        public string Name { get; set; }
        public string REFERENCE { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ReferenceACCT { get; set; }
        public string ReferenceOrg { get; set; }
        public string IBAN { get; set; }
        public DateTime? OpenDate { get; set; }
        public bool ExternallyManged  { get; set; }
        public short? STATUS { get; set; }

        // // Foreign key
        // public DEF_CIF DEF_CIF { get; set; }
        // public DEF_ACCT_CLASS DEF_ACCT_CLASS { get; set; }
    }
}

        