// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SIS.OpenCore.Shared.Model.Common;
#nullable disable

namespace SIS.OpenCore.Shared.Model.Objects.Product
{
    public partial class LUT_PRODUCT_CHANNEL : BaseLUTEntity
    {
    }
}