// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Model
{
    public partial class LUT_COUNTRY
    {
        public short ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    }
}