// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SIS.OpenCore.Shared.Model.Common;


namespace SIS.OpenCore.Shared.Model.Transactions.Posting
{
    public partial class LUT_POSTING_CHANNEL : BaseLUTEntity
    {
    }
}