// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using SIS.OpenCore.Shared.Model;

#nullable disable

namespace SIS.OpenCore.Shared.Model.Objects.CIF
{
    public partial class LUT_CIF_TYPE : BaseLUTEntity
    {
        public ICollection<DEF_CIF_CLASS> DEF_CIF_CLASS { get; } = new List<DEF_CIF_CLASS>();
    }
}