// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using SIS.OpenCore.Shared.Model.Objects.GL;

#nullable disable

namespace SIS.OpenCore.Shared.Model.Objects.UserData
{
    public partial class Company  : BaseUserData
	{
    }
}