// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using SIS.OpenCore.Shared.Model.Common;
using SIS.OpenCore.Shared.Model.Objects.CIF;

#nullable disable

namespace SIS.OpenCore.Shared.Model.Objects.Account.CK
{
    public partial class BaseCIFACCT : BaseEntity //BaseCIFACCT
    {
        virtual public int GetPrimaryKey()
        {
            throw new NotImplementedException();
        }
    }
}

        