USE [OpenCore]
GO

/****** Object:  Table [dbo].[DEF_CIF_Company]    Script Date: 17/12/2019 13:18:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEF_CIF_Company](
	[DEF_CIF_Company_ID] [int] IDENTITY(1,1) NOT NULL,
	[CIF_NO] [nvarchar](max) NULL,
	[Company_ID] [smallint] NULL,
 CONSTRAINT [PK_DEF_CIF_Company] PRIMARY KEY CLUSTERED 
(
	[DEF_CIF_Company_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

