USE [OpenCore]
GO

/****** Object:  Table [dbo].[DEF_Branch]    Script Date: 17/12/2019 13:16:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEF_Branch](
	[ID] [smallint] NOT NULL,
	[Name] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_DEF_Branch] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

