USE [OpenCore]
GO

/****** Object:  Table [dbo].[DEF_CIF_CLASS]    Script Date: 17/12/2019 13:17:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS	(  SELECT [name] FROM sys.tables WHERE [name] = 'DEF_CIF_CLASS' )
	CREATE TABLE [dbo].[DEF_CIF_CLASS](
		[Code] nvarchar(10) NOT NULL,
		[Name] nvarchar(80) NOT NULL,
		[Type] nvarchar(10) NOT NULL,
		[CompanyNo] smallint NOT NULL,
		[EFFECTIVE_DT] [datetime] NULL,
		[REFERENCE] [nvarchar](max) NULL,
	 CONSTRAINT [PK__DEF_CIF___A25C5AA6127E02BB] PRIMARY KEY CLUSTERED 
	(
		[Code] ASC,
		[CompanyNo] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
	GO

ALTER TABLE DEF_CIF_CLASS
DROP PK__DEF_CIF___A25C5AA6127E02BB;
GO

ALTER TABLE DEF_CIF_CLASS
ALTER COLUMN [CompanyNo] smallint NOT NULL;
GO

ALTER TABLE DEF_CIF_CLASS
ALTER COLUMN [Type] tinyint NOT NULL;

/****** Object:  Index [PK__DEF_CIF___A25C5AA6127E02BB]    Script Date: 18/12/2019 15:08:33 ******/
ALTER TABLE [dbo].[DEF_CIF_CLASS] ADD  CONSTRAINT [PK__DEF_CIF___A25C5AA6127E02BB] PRIMARY KEY CLUSTERED 
(
	[Code] ASC,
	[CompanyNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




