USE [OpenCore]
GO

/****** Object:  Table [dbo].[LUT_CIF_TYPE]    Script Date: 17/12/2019 13:22:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS	(  SELECT [name] FROM sys.tables WHERE [name] = 'LUT_CIF_TYPE' )
	CREATE TABLE [dbo].[LUT_CIF_TYPE](
		[Code] [smallint] NOT NULL,
		[Name] [nvarchar](80) NULL,
	 CONSTRAINT [PK__LUT_CIF___A25C5AA6A1F27BC6] PRIMARY KEY CLUSTERED 
	(
		[Code] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

ALTER TABLE [dbo].[LUT_CIF_TYPE] 
DROP CONSTRAINT [PK__LUT_CIF___A25C5AA6A1F27BC6] WITH ( ONLINE = OFF )
GO

ALTER TABLE [dbo].[LUT_CIF_TYPE] 
ALTER COLUMN Code tinyint NOT NULL;

ALTER TABLE [dbo].[LUT_CIF_TYPE] 
ADD  CONSTRAINT [PK__LUT_CIF___A25C5AA6A1F27BC6] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



