USE [OpenCore]
GO

/****** Object:  Table [dbo].[LUT_GL_ACCT_CATEGORY]    Script Date: 16/02/2020 14:44:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LUT_AE_CATEGORY](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](80) NOT NULL,
	[Description] [nvarchar](80) NULL,
	[ParentCat] [smallint] NULL,
 CONSTRAINT [PK_LUT_AE_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


