// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Model
{
    public partial class DEF_CIF_CLASS
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public byte Type { get; set; }
        public short CompanyNo { get; set; }
        public DateTime? EFFECTIVE_DT { get; set; }
        public string REFERENCE { get; set; }
    }
}