// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Model
{
    public partial class DEF_GL
    {
        public int GL_DEFID { get; set; }
        public byte? Zone { get; set; }
        public short CompanyNo { get; set; }
        public short? BranchNo { get; set; }
        public byte? SectorNo { get; set; }
        public byte? DepNo { get; set; }
        public byte? UnitNO { get; set; }
        public short? ProductNo { get; set; }
        public byte Nature { get; set; }
        public byte PostingLevel { get; set; }
        public int LedgerNO { get; set; }
        public string GL { get; set; }
        public string CURR { get; set; }
        public string COMMENTS { get; set; }
        public DateTime EFFECTIVE_DT { get; set; }
        public byte STATUS { get; set; }
        public string REFERENCE { get; set; }
    }
}