// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Model
{
    public partial class DEF_FIXRATE_ACCT_DATES
    {
        public int DEF_FIXRATE_ACCT_DATES_ID { get; set; }
        public int DEF_ACCT_ID { get; set; }
        public string ACCT_NO { get; set; }
        public DateTime ACCT_DATE { get; set; }
    }
}