// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SIS.OpenCore.Model
{
    public partial class LUT_ACCT_TYPE
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}