// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SIS.OpenCore.Model
{
    public partial class LUT_LedgerNature
    {
        public byte ID { get; set; }
        public string Name { get; set; }
        public string CR_DR { get; set; }
    }
}