// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Model
{
    public partial class PROC_FIXRATE_INTEREST
    {
        public int PROC_FIXRATE_INTEREST_ID { get; set; }
        public string CIF_NO { get; set; }
        public string ACCT_NO { get; set; }
        public decimal PRINCIPLE_AMT { get; set; }
        public decimal CALC_INTEREST_AMT { get; set; }
        public DateTime FROM_DATE { get; set; }
        public DateTime TO_DATE { get; set; }
        public byte STATUS_ID { get; set; }
    }
}