// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Model
{
    public partial class Settings
    {
        public int VerID { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public string GLFormat { get; set; }
        public string GLFormatDigits { get; set; }
        public string BaseCurrency { get; set; }
        public string ACCTFormatDigits { get; set; }
        public string ACCTFormatDigitsNum { get; set; }
        public string ACCTFormat { get; set; }
        public string CIFFormatDigits { get; set; }
    }
}