// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Model
{
    public partial class DEF_CIF_Company
    {
        public int DEF_CIF_Company_ID { get; set; }
        public string CIF_NO { get; set; }
        public short? Company_ID { get; set; }
    }
}