// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Shared.Model.Common
{
    public partial class Currency : BaseEntity
    {
        public int GetPrimaryKey ()
        {
            return CurrencyID;
        }

        public short CurrencyID { get; set; }
        public string ISOCode { get; set; }
        public string Symbol { get; set; }
        public short Fractions { get; set; }
        public string Name { get; set; }
    }
}