// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Shared.Model
{
    public partial class DEF_FIXRATE_ACCT
    {
        public int DEF_ACCT_ID { get; set; }
        public string CIF_NO { get; set; }
        public string ACCT_NO { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ReferenceACCT { get; set; }
        public string ReferenceOrg { get; set; }
        public string IBAN { get; set; }
        public string ACCT_TYPE { get; set; }
        public string ACCT_CLASS { get; set; }
        public string Currency { get; set; }
        public DateTime OpenDate { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime CloseDate { get; set; }
        public decimal Principle { get; set; }
        public decimal? Rate { get; set; }
        public short? AccrualBasis { get; set; }
        public string CSP_Code { get; set; }
        public short CompanyNo { get; set; }
        public short STATUS_ID { get; set; }
    }
}