// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Shared.Model
{
    public partial class LUT_CIF_TYPE
    {
        public short Code { get; set; }
        public string Name { get; set; }
    }
}