// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Shared.Model
{
    public partial class LUT_TRN_STATUS
    {
        public short STATUS_ID { get; set; }
        public string NAME { get; set; }
    }
}