// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIS.OpenCore.Shared.Model
{
    public partial class SP_AddCIF_EXT1Result
    {
    }
}
