// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIS.OpenCore.Shared.Model
{
    public partial class VW_DEF_GL
    {
        public string GL { get; set; }
        public short Zone { get; set; }
        public string ZoneName { get; set; }
        public short CompanyNo { get; set; }
        public string CompanyName { get; set; }
        public short BranchNo { get; set; }
        public string BranchName { get; set; }
        public short SectorNo { get; set; }
        public string SectorName { get; set; }
        public short DepNo { get; set; }
        public string DepName { get; set; }
        public short UnitNO { get; set; }
        public string UnitName { get; set; }
        public short ProductNo { get; set; }
        public short Nature { get; set; }
        public string NatureName { get; set; }
        public string CR_DR { get; set; }
        public int LedgerNO { get; set; }
        public string CURR { get; set; }
        public DateTime EFFECTIVE_DT { get; set; }
        public string REFERENCE { get; set; }
    }
}